export const PRODUCTS = [
  {
    title: 'Essentials Hoodie',
    price: '564.00',
    describe:
      'The signature fleece hoodie is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. A kangaroo pocket, rib-knit cuffs, and waist hem frame the piece. An Essentials rubberized label is stitched on the double-layered hood.',
    slug: 'sit-illum-voluptas-essentials-hoodie',
    color: 'coral',
    brand: 'ESSENTIALS',
    categoryId: 99,
    categoryName: 'ESSENTIALS MENS',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/192SU222052F_ESSENTIALS_HOODIE_CORAL-Front_1920x.jpg?v=1660094071',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/192SU222052F_ESSENTIALS_HOODIE_CORAL-Back_1920x.jpg?v=1660094071',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/192SU222052F_ESSENTIALS_HOODIE_CORAL-Detail_1920x.jpg?v=1660094071',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/192SU222052F_ESSENTIALS_HOODIE_CORAL-Detail2_1920x.jpg?v=1660094071',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '1',
  },
  {
    title: 'Essentials Sweatpant',
    price: '564.00',
    describe:
      'The signature fleece sweatpant is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. An Essentials rubberized label is stitched on the center front.',
    slug: 'sit-illum-voluptas-essentials-sweatpant',
    color: 'coral',
    brand: 'ESSENTIALS',
    categoryId: 99,
    categoryName: 'ESSENTIALS MENS',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/130SU222022F_ESSENTIALS_SWEATPANTS_CORAL-Front_1920x.jpg?v=1660094070',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/130SU222022F_ESSENTIALS_SWEATPANTS_CORAL-Back_1920x.jpg?v=1660094070',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/130SU222022F_ESSENTIALS_SWEATPANTS_CORAL-Detail_1920x.jpg?v=1660094070',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/130SU222022F_ESSENTIALS_SWEATPANTS_CORAL-Detail2_1920x.jpg?v=1660094070',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '2',
  },
  {
    title: 'Essentials Hoodie',
    price: '564.00',
    describe:
      'The signature fleece hoodie is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. A kangaroo pocket, rib-knit cuffs, and waist hem frame the piece. An Essentials rubberized label is stitched on the double-layered hood.',
    slug: 'sit-illum-voluptas-essentials-hoddie-egg',
    color: 'egg shell',
    brand: 'ESSENTIALS',
    categoryId: 99,
    categoryName: 'ESSENTIALS MENS',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/130SU222022F_ESSENTIALS_SWEATPANTS_CORAL-Front_1920x.jpg?v=1660094070',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/130SU222022F_ESSENTIALS_SWEATPANTS_CORAL-Back_1920x.jpg?v=1660094070',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/130SU222022F_ESSENTIALS_SWEATPANTS_CORAL-Detail_1920x.jpg?v=1660094070',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/130SU222022F_ESSENTIALS_SWEATPANTS_CORAL-Detail2_1920x.jpg?v=1660094070',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '3',
  },
  {
    title: 'Essentials Sweatpant',
    price: '564.00',
    describe:
      'The signature fleece hoodie is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. A kangaroo pocket, rib-knit cuffs, and waist hem frame the piece. An Essentials rubberized label is stitched on the double-layered hood.',
    slug: 'sit-illum-voluptas-essentials-Sweatpant-egg',
    color: 'egg shell',
    brand: 'ESSENTIALS',
    categoryId: 99,
    categoryName: 'ESSENTIALS MENS',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/130SU222020F_ESSENTIALS_SWEATPANT_EGG_SHELL-Front_1920x.jpg?v=1660094073',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/130SU222020F_ESSENTIALS_SWEATPANT_EGG_SHELL-Back_1920x.jpg?v=1660094073',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/130SU222020F_ESSENTIALS_SWEATPANT_EGG_SHELL-Detail_1920x.jpg?v=1660094073',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/130SU222020F_ESSENTIALS_SWEATPANT_EGG_SHELL-Detail2_1920x.jpg?v=1660094073',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '4',
  },
  {
    title: 'Essentials Hoodie',
    price: '564.00',
    describe:
      'The signature fleece hoodie is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. A kangaroo pocket, rib-knit cuffs, and waist hem frame the piece. An Essentials rubberized label is stitched on the double-layered hood.',
    slug: 'sit-illum-voluptas-essentials-hoddie-egg',
    color: 'smoke',
    brand: 'ESSENTIALS',
    categoryId: 99,
    categoryName: 'ESSENTIALS MENS',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/192SU222051F_ESSENTIALS_HOODIE_SMOKE-Front_1920x.jpg?v=1660094079',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/192SU222051F_ESSENTIALS_HOODIE_SMOKE-Back_1920x.jpg?v=1660094079',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/192SU222051F_ESSENTIALS_HOODIE_SMOKE-Detail_1920x.jpg?v=1660094079',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/192SU222051F_ESSENTIALS_HOODIE_SMOKE-Detail2_1920x.jpg?v=1660094079',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '5',
  },
  {
    title: 'Essentials Sweatpant',
    price: '564.00',
    describe:
      'The signature fleece hoodie is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. A kangaroo pocket, rib-knit cuffs, and waist hem frame the piece. An Essentials rubberized label is stitched on the double-layered hood.',
    slug: 'sit-illum-voluptas-essentials-hoddie-egg',
    color: 'smoke',
    brand: 'ESSENTIALS',
    categoryId: 99,
    categoryName: 'ESSENTIALS MENS',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/Front_506453a8-1887-4236-9f33-6c47f88a1d29_1920x.jpg?v=1660689714',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/Back_27d65a39-74f0-43b2-a211-bddecd6d6dac_1920x.jpg?v=1660689714',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/Detail_858a55e2-8107-4d16-84ce-3fc54c5d5ea3_1920x.jpg?v=1660689714',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/Detail2_338d77d4-7560-4d21-a336-41003268aa55_1920x.jpg?v=1660689714',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '6',
  },
  {
    title: 'Long Coat',
    price: '564.00',
    describe:
      'The signature fleece hoodie is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. A kangaroo pocket, rib-knit cuffs, and waist hem frame the piece. An Essentials rubberized label is stitched on the double-layered hood.',
    slug: 'sit-illum-voluptas-essentials-hoddie-egg',
    color: 'egg shell',
    brand: 'ESSENTIALS',
    categoryId: 99,
    categoryName: 'ESSENTIALS MENS',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU224000F_LONG_COAT_EGG_SHELL-Front_1920x.jpg?v=1660094079',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU224000F_LONG_COAT_EGG_SHELL-Back_1920x.jpg?v=1660094078',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU224000F_LONG_COAT_EGG_SHELL-Detail_1920x.jpg?v=1660094078',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU224000F_LONG_COAT_EGG_SHELL-Detail2_1920x.jpg?v=1660094078',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '7',
  },
  {
    title: 'Barn Vest',
    price: '564.00',
    describe:
      'The signature fleece hoodie is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. A kangaroo pocket, rib-knit cuffs, and waist hem frame the piece. An Essentials rubberized label is stitched on the double-layered hood.',
    slug: 'sit-illum-voluptas-essentials-hoddie-egg',
    color: 'egg shell',
    brand: 'ESSENTIALS',
    categoryId: 99,
    categoryName: 'ESSENTIALS MENS',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU222020F_VEST_EGG_SHELL-Front_1920x.jpg?v=1660094071',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU222020F_VEST_EGG_SHELL-Back_1920x.jpg?v=1660094071',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU222020F_VEST_EGG_SHELL-Detail_1920x.jpg?v=1660094071',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU222020F_VEST_EGG_SHELL-Detail_1920x.jpg?v=1660094071',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '8',
  },
  {
    title: 'Long Coat',
    price: '564.00',
    describe:
      'The signature fleece hoodie is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. A kangaroo pocket, rib-knit cuffs, and waist hem frame the piece. An Essentials rubberized label is stitched on the double-layered hood.',
    slug: 'sit-illum-voluptas-essentials-hoddie-egg',
    color: 'smoke',
    brand: 'ESSENTIALS',
    categoryId: 99,
    categoryName: 'ESSENTIALS MENS',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU224001F_LONG_COAT_SMOKE-Front_1920x.jpg?v=1660094079',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU224001F_LONG_COAT_SMOKE-Back_1920x.jpg?v=1660094079',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU224001F_LONG_COAT_SMOKE-Detail_1920x.jpg?v=1660094079',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU224001F_LONG_COAT_SMOKE-Detail2_1920x.jpg?v=1660094079',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '9',
  },
  {
    title: 'Barn Vest',
    price: '564.00',
    describe:
      'The signature fleece hoodie is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. A kangaroo pocket, rib-knit cuffs, and waist hem frame the piece. An Essentials rubberized label is stitched on the double-layered hood.',
    slug: 'sit-illum-voluptas-essentials-hoddie-egg',
    color: 'egg shell',
    brand: 'ESSENTIALS',
    categoryId: 99,
    categoryName: 'ESSENTIALS MENS',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU222021F_VEST_SMOKE-Front_1920x.jpg?v=1660094073',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU222021F_VEST_SMOKE-Back_1920x.jpg?v=1660094073',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU222021F_VEST_SMOKE-Detail_1920x.jpg?v=1660094073',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU222021F_VEST_SMOKE-Detail2_1920x.jpg?v=1660094073',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '10',
  },
  {
    title: 'Relaxed Trouser',
    price: '564.00',
    describe:
      'The signature fleece hoodie is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. A kangaroo pocket, rib-knit cuffs, and waist hem frame the piece. An Essentials rubberized label is stitched on the double-layered hood.',
    slug: 'sit-illum-voluptas-essentials-hoddie-egg',
    color: 'egg shell',
    brand: 'ESSENTIALS',
    categoryId: 99,
    categoryName: 'ESSENTIALS MENS',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/130SU222080F_RELAXED_TROUSER_EGG_SHELL-Front_1920x.jpg?v=1660094068',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/130SU222080F_RELAXED_TROUSER_EGG_SHELL-Back_1920x.jpg?v=1660094068',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/130SU222080F_RELAXED_TROUSER_EGG_SHELL-Detail_1920x.jpg?v=1660094068',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/Look_036_afa332a7-452c-4646-9918-e7aa76cbe476_1920x.jpg?v=1661215421',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '11',
  },
  {
    title: 'Dock Short',
    price: '564.00',
    describe:
      'The signature fleece hoodie is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. A kangaroo pocket, rib-knit cuffs, and waist hem frame the piece. An Essentials rubberized label is stitched on the double-layered hood.',
    slug: 'sit-illum-voluptas-essentials-hoddie-egg',
    color: 'egg shell',
    brand: 'ESSENTIALS',
    categoryId: 99,
    categoryName: 'ESSENTIALS MENS',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/160SU224030F_DOCK_SHORT_EGG_SHELL-Front_1920x.jpg?v=1660094071',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/160SU224030F_DOCK_SHORT_EGG_SHELL-Back_1920x.jpg?v=1660094071',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/160SU224030F_DOCK_SHORT_EGG_SHELL-Detail_1920x.jpg?v=1660094071',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/Look_039_a42f88a3-080b-4a5f-8caa-ef49d0e5f35e_1920x.jpg?v=1661217084',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '12',
  },
  {
    title: 'Cable Knit',
    price: '564.00',
    describe:
      'The signature fleece hoodie is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. A kangaroo pocket, rib-knit cuffs, and waist hem frame the piece. An Essentials rubberized label is stitched on the double-layered hood.',
    slug: 'sit-illum-voluptas-essentials-hoddie-egg',
    color: 'coral',
    brand: 'ESSENTIALS',
    categoryId: 99,
    categoryName: 'ESSENTIALS MENS',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/125SU224062F_CABLE_KNIT_CORAL-Front_1920x.jpg?v=1660094074',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/125SU224062F_CABLE_KNIT_CORAL-Back_1920x.jpg?v=1660094074',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/125SU224062F_CABLE_KNIT_CORAL-Detail_1920x.jpg?v=1660094074',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/125SU224062F_CABLE_KNIT_CORAL-Detail2_1920x.jpg?v=1660094074',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '13',
  },
  {
    title: 'Bucket Hat',
    price: '564.00',
    describe:
      'The signature fleece hoodie is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. A kangaroo pocket, rib-knit cuffs, and waist hem frame the piece. An Essentials rubberized label is stitched on the double-layered hood.',
    slug: 'sit-illum-voluptas-essentials-hoddie-egg',
    color: 'coral',
    brand: 'ESSENTIALS',
    categoryId: 99,
    categoryName: 'ESSENTIALS MENS',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/1_9ece1dd2-419c-46d8-8a33-3399aec6dad1_1920x.jpg?v=1660349636',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/2_9a354249-db0e-4514-b6f4-adec56b2ab0e_1920x.jpg?v=1660349639',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/4_b52f7b52-b681-49cc-a536-9fa8eca5169a_1920x.jpg?v=1660349639',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/3_cec39d11-1690-4131-99d2-6246244c7065_1920x.jpg?v=1660349639',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '14',
  },
  {
    title: 'Coaches Jacket',
    price: '564.00',
    describe:
      'The signature fleece hoodie is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. A kangaroo pocket, rib-knit cuffs, and waist hem frame the piece. An Essentials rubberized label is stitched on the double-layered hood.',
    slug: 'sit-illum-voluptas-essentials-hoddie-egg',
    color: 'egg shell',
    brand: 'ESSENTIALS',
    categoryId: 99,
    categoryName: 'ESSENTIALS MENS',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU222090F_COACHES_JACKET_EGG_SHELL-Back_1920x.jpg?v=1660757726',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU222090F_COACHES_JACKET_EGG_SHELL-Front_1920x.jpg?v=1660757726',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU222090F_COACHES_JACKET_EGG_SHELL-Detail_1920x.jpg?v=1660094071',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU222090F_COACHES_JACKET_EGG_SHELL-Detail2_1920x.jpg?v=1660094071',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '15',
  },
  {
    title: 'LS Tee',
    price: '564.00',
    describe:
      'The signature fleece hoodie is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. A kangaroo pocket, rib-knit cuffs, and waist hem frame the piece. An Essentials rubberized label is stitched on the double-layered hood.',
    slug: 'sit-illum-voluptas-essentials-hoddie-egg',
    color: 'egg shell',
    brand: 'ESSENTIALS',
    categoryId: 99,
    categoryName: 'ESSENTIALS MENS',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/125SU222010F_LS_TEE_EGG_SHELL-front_1920x.jpg?v=1660094071',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/125SU222010F_LS_TEE_EGG_SHELL-Back_1920x.jpg?v=1660094071',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/125SU222010F_LS_TEE_EGG_SHELL-Detail_1920x.jpg?v=1660094071',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/125SU222010F_LS_TEE_EGG_SHELL-Detail2_1920x.jpg?v=1660094071',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '16',
  },
  {
    title: 'Trucker Jacket',
    price: '564.00',
    describe:
      'The signature fleece hoodie is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. A kangaroo pocket, rib-knit cuffs, and waist hem frame the piece. An Essentials rubberized label is stitched on the double-layered hood.',
    slug: 'sit-illum-voluptas-essentials-hoddie-egg',
    color: 'indigo',
    brand: 'ESSENTIALS',
    categoryId: 99,
    categoryName: 'ESSENTIALS MENS',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU224140F_TRUCKER_JACKET_INDIGO-Front_1920x.jpg?v=1660094080',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU224140F_TRUCKER_JACKET_INDIGO-Back_1920x.jpg?v=1660094080',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU224140F_TRUCKER_JACKET_INDIGO-Detail_1920x.jpg?v=1660094080',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/202SU224140F_TRUCKER_JACKET_INDIGO-Detail2_1920x.jpg?v=1660094080',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '17',
  },
  {
    title: '5 Pocket Jean',
    price: '564.00',
    describe:
      'The signature fleece hoodie is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. A kangaroo pocket, rib-knit cuffs, and waist hem frame the piece. An Essentials rubberized label is stitched on the double-layered hood.',
    slug: 'sit-illum-voluptas-essentials-hoddie-egg',
    color: 'indigo',
    brand: 'ESSENTIALS',
    categoryId: 99,
    categoryName: 'ESSENTIALS MENS',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/130SU222022F_ESSENTIALS_SWEATPANTS_CORAL-Front_1920x.jpg?v=1660094070',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/Back_c5518129-1aa8-4f1d-88d7-2f00748e28f1_1920x.jpg?v=1660689497',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/Detail2_8e5b602a-9fe8-40ad-9f5b-7d8b70ffaf8d_1920x.jpg?v=1660689497',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/Detail_b3b7e599-ec36-4b0d-9950-9103e58bc778_1920x.jpg?v=1660689497',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '18',
  },
  {
    title: 'ESSENTIALS RC 9FIFTY CAP',
    price: '564.00',
    describe:
      'The signature fleece hoodie is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. A kangaroo pocket, rib-knit cuffs, and waist hem frame the piece. An Essentials rubberized label is stitched on the double-layered hood.',
    slug: 'sit-illum-voluptas-essentials-hoddie-egg',
    color: 'black',
    brand: 'ESSENTIALS',
    categoryId: 99,
    categoryName: 'ESSENTIALS MENS',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/Essentials-Black-Front_6399a8a4-9e7e-40b4-b9f1-64e40657c98e_1920x.jpg?v=1638400073',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/Essentials-Black-FrontAngle_7e3c1602-ac24-4fb0-94ac-1f764e64bbdc_1920x.jpg?v=1638400073',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/Essentials-Black-BackAngle_2e0d567a-26b4-449c-be8d-3c9980827438_1920x.jpg?v=1638400073',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/Essentials-Black-UV_1920x.jpg?v=1638400073',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '19',
  },
  {
    title: 'The California',
    price: '564.00',
    describe:
      'The signature fleece hoodie is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. A kangaroo pocket, rib-knit cuffs, and waist hem frame the piece. An Essentials rubberized label is stitched on the double-layered hood.',
    slug: 'sit-illum-voluptas-essentials-hoddie-egg',
    color: 'egg shell',
    brand: 'FEAR OF GOD',
    categoryId: 99,
    categoryName: 'ESSENTIALS MENS',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/FGE80-100EVA_CALIFORNIA_GREIGE_1_1920x.jpg?v=1660691599',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/FGE80-100EVA_CALIFORNIA_GREIGE_2_1920x.jpg?v=1660691599',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/FGE80-100EVA_CALIFORNIA_GREIGE_5_1920x.jpg?v=1660691599',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: 'https://cdn.shopify.com/s/files/1/1003/3354/products/FGE80-100EVA_CALIFORNIA_GREIGE_6_1920x.jpg?v=1660691599',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '20',
  },
  {
    title: 'Tee white',
    price: '564.00',
    describe:
      'The signature fleece hoodie is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. A kangaroo pocket, rib-knit cuffs, and waist hem frame the piece. An Essentials rubberized label is stitched on the double-layered hood.',
    slug: 'sit-illum-voluptas-essentials-hoddie-egg',
    color: 'White',
    brand: 'MOS',
    categoryId: 99,
    categoryName: 'MOS Limit',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: '/df-week1/mos/tee-white/tee-white-1.jpeg',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: '/df-week1/mos/tee-white/tee-white-2.jpeg',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: '/df-week1/mos/tee-white/tee-white-3.jpeg',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: '/df-week1/mos/tee-white/tee-white-4.jpeg',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '21',
  },
  {
    title: 'Tee black',
    price: '564.00',
    describe:
      'The signature fleece hoodie is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. A kangaroo pocket, rib-knit cuffs, and waist hem frame the piece. An Essentials rubberized label is stitched on the double-layered hood.',
    slug: 'sit-illum-voluptas-essentials-hoddie-egg',
    color: 'Black',
    brand: 'MOS',
    categoryId: 99,
    categoryName: 'MOS Limit',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: '/df-week1/mos/tee-black/tee-black-1.jpeg',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: '/df-week1/mos/tee-black/tee-black-2.jpeg',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: '/df-week1/mos/tee-black/tee-black-3.jpeg',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: '/df-week1/mos/tee-black/tee-black-4.jpeg',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '22',
  },
  {
    title: 'Tee green',
    price: '564.00',
    describe:
      'The signature fleece hoodie is detailed with an Essentials Fear of God logo in a tonal velvet flocking reminiscent of vintage athletic school uniforms. A kangaroo pocket, rib-knit cuffs, and waist hem frame the piece. An Essentials rubberized label is stitched on the double-layered hood.',
    slug: 'sit-illum-voluptas-essentials-hoddie-egg',
    color: 'Green',
    brand: 'MOS',
    categoryId: 99,
    categoryName: 'MOS Limit',
    sizes: ['small', 'large', 'medium', 'extraLarge'],
    images: [
      {
        tile: 'Ergonomic Granite Ball',
        url: '/df-week1/mos/tee-green/tee-green-1.jpeg',
      },
      {
        tile: 'Recycled Wooden Chair',
        url: '/df-week1/mos/tee-green/tee-green-2.jpeg',
      },
      {
        tile: 'Refined Plastic Gloves',
        url: '/df-week1/mos/tee-green/tee-green-3.jpeg',
      },
      {
        tile: 'Recycled Plastic Salad',
        url: '/df-week1/mos/tee-green/tee-green-4.jpeg',
      },
    ],
    detail: [
      'CLASSIC ESSENTIALS FIT',
      '80% COTTON / 20% POLYESTER HEAVYWEIGHT FLEECE',
      'ESSENTIALS FEAR OF GOD FLOCKED LOGO ON CHEST',
      'ESSENTIALS RUBBERIZED LABEL',
      'RIB-KNIT CUFFS AND WAIST HEM',
      'KANGAROO POCKET',
      'IMPORTED',
      'ESSENTIALS PRODUCTS ARE CURRENTLY NOT AVAILABLE FOR PURCHASE OR SHIPMENT TO EUROPE INCLUDING BELGIUM, LUXEMBOURG, AND THE NETHERLANDS.',
    ],
    id: '23',
  },
];
